version: '3.8'
services:
  ecommerce:
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlserver:3306/ecommercedb
    networks:
      - ecommercenet
    depends_on:
      - mysqlserver
  mysqlserver:
    image: mysql:8.0
    container_name: mysqlserver
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=ecommercedb
    networks:
      - ecommercenet
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config:
networks:
  ecommercenet:
